DROP TABLE IF EXISTS TBL_TASKS;
 
CREATE TABLE TBL_TASKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  status VARCHAR(250) NOT NULL,
  created_at VARCHAR(250) NOT NULL
);